[package]
name = "godot-pack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { version = "0.3.5", features = ["register-docs"]}
regex = "1.11.3"
